name: Semantic Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@9
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
